version: '3.0'
services:
  app:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - ./app:/app
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}




















# version: "3.8"

# services:
#   app:
#     build:
#     ports:
#       - "8000:8000"
#     volumes:
#       -./app:/app
#    command: >
#      sh -c "python manage.py runserver 0.0.0.0:8000"